script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without documentation"
before_install:
  - gem update --system 2.1.11
  - gem --version
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
env:
  - RAILS_VERSION=master
  - RAILS_VERSION=4-2-stable
  - RAILS_VERSION=4-1-stable
  - RAILS_VERSION=4-0-stable
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=3-1-stable
matrix:
  allow_failures:
    - env: RAILS_VERSION=master
