# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty
script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without documentation"
before_install:
  - script/update_rubygems_and_install_bundler
  - gem --version
matrix:
  include:
    # Rails dev / 6 builds >= 2.5.0
    - rvm: 2.6.2
      env: RAILS_VERSION=master
    - rvm: 2.5.5
      env: RAILS_VERSION=master

    # Rails 5.2 builds >= 2.2.2
    - rvm: 2.5.5
      env: RAILS_VERSION='~> 5.2.0'
    - rvm: 2.4.6
      env: RAILS_VERSION='~> 5.2.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 5.2.0'
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 5.2.0'

    # Rails 5.1 Builds >= 2.2.2
    - rvm: 2.5.5
      env: RAILS_VERSION='~> 5.1.0'
    - rvm: 2.4.6
      env: RAILS_VERSION='~> 5.1.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 5.1.0'
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 5.1.0'

    # Rails 5.0 Builds >= 2.2.2
    - rvm: 2.5.5
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.4.6
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 5.0.0'

    # Rails 4.2 Builds >= 1.9.3
    - rvm: 2.4.6
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.4.6
      env: RAILS_VERSION=4-2-stable
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.3.8
      env: RAILS_VERSION=4-2-stable
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.2.10
      env: RAILS_VERSION=4-2-stable
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.1.10
      env: RAILS_VERSION=4-2-stable
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.0.0
      env: RAILS_VERSION=4-2-stable
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 1.9.3
      env: RAILS_VERSION=4-2-stable

    # Rails 4.1 Builds >= 1.9.3, < 2.4
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 2.3.8
      env: RAILS_VERSION=4-1-stable
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 2.2.10
      env: RAILS_VERSION=4-1-stable
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 2.1.10
      env: RAILS_VERSION=4-1-stable
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 2.0.0
      env: RAILS_VERSION=4-1-stable
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 1.9.3
      env: RAILS_VERSION=4-1-stable

    # Rails 4.0 Builds >= 1.8.11, < 2.4
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 2.3.8
      env: RAILS_VERSION=4-0-stable
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 2.2.10
      env: RAILS_VERSION=4-0-stable
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 2.1.10
      env: RAILS_VERSION=4-0-stable
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 2.0.0
      env: RAILS_VERSION=4-0-stable
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 1.9.3
      env: RAILS_VERSION=4-0-stable

    # Rails 3.2 Builds < 2.4
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 2.3.8
      env: RAILS_VERSION=3-2-stable
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 2.2.10
      env: RAILS_VERSION=3-2-stable
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 2.1.10
      env: RAILS_VERSION=3-2-stable
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 2.0.0
      env: RAILS_VERSION=3-2-stable
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 1.9.3
      env: RAILS_VERSION=3-2-stable
    - rvm: 1.9.2
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 1.9.2
      env: RAILS_VERSION=3-2-stable
    - rvm: 1.8.7
      env: RAILS_VERSION='~> 3.2.17'
    - rvm: 1.8.7
      env: RAILS_VERSION=3-2-stable

    # Rails 3.1 Builds, < 2.2
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 3.1.12'
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 3.1.12'
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 3.1.12'
    - rvm: 1.9.2
      env: RAILS_VERSION='~> 3.1.12'
    - rvm: 1.8.7
      env: RAILS_VERSION='~> 3.1.12'

    # Rails 3.0 Builds, < 2
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 3.0.20'
    - rvm: 1.9.2
      env: RAILS_VERSION='~> 3.0.20'
    - rvm: 1.8.7
      env: RAILS_VERSION='~> 3.0.20'

  allow_failures:
    - env: RAILS_VERSION=master

  fast_finish: true

branches:
  only:
    - master
    - /^\d+-\d+-maintenance$/
